Types and operators homework
vashaferov/TMS_AQA pull request #1
Opened 2023-11-17 06:45 UTC by vashaferov

2023-11-18 19:47 UTC, wildpioneer requested changes

2023-11-18 19:47 UTC, wildpioneer commented on TMS_AQA/Program.cs
> +while (flag)
1. На этом занятии мы еше не знали циклов ;) - ну да ладно. 
2. do-while будет уместнее?

2023-11-18 19:47 UTC, wildpioneer commented on TMS_AQA/Program.cs
> +                    Console.Write("Введите второе число: ");
Логические блоки программы лучше всего выделять пустыми строками для более комфортного чтения

2023-11-18 19:47 UTC, wildpioneer commented on TMS_AQA/Program.cs
> +                                Console.WriteLine($"{firstNum} / {secondNum} = Ошибка! Делить на ноль нельзя!\n");
Зачем здесь перевод на новую строку - если WriteLine это и так сделает?

2023-11-18 19:47 UTC, wildpioneer commented on TMS_AQA/Program.cs
> +                            Console.WriteLine("Ошибка! Неизвестная операция!\n");
Зачем здесь перевод на новую строку - если WriteLine это и так сделает?

2023-11-18 19:47 UTC, wildpioneer commented on TMS_AQA/Program.cs
> +                    Console.WriteLine("Ошибка! Неверный формат ввода, введите число!\n");
Зачем здесь перевод на новую строку - если WriteLine это и так сделает?

2023-11-18 19:47 UTC, wildpioneer commented on TMS_AQA/Program.cs
> +                            Console.WriteLine("Ошибка! Число не попало в исходный диапозн\n");
Зачем здесь перевод на новую строку - если WriteLine это и так сделает?

2023-11-18 19:47 UTC, wildpioneer commented on TMS_AQA/Program.cs
> +                                Console.WriteLine("Число не входит в промежутки\n");
Зачем здесь перевод на новую строку - если WriteLine это и так сделает?

2023-11-18 19:47 UTC, wildpioneer commented on TMS_AQA/Program.cs
> +                                Console.WriteLine("Число входит в промежуток [-40; -10]\n");
Зачем здесь перевод на новую строку - если WriteLine это и так сделает?

2023-11-18 19:47 UTC, wildpioneer commented on TMS_AQA/Program.cs
> +                                Console.WriteLine("Число входит в промежуток [-9; 0]\n");
Зачем здесь перевод на новую строку - если WriteLine это и так сделает?

2023-11-18 19:47 UTC, wildpioneer commented on TMS_AQA/Program.cs
> +                                Console.WriteLine("Число входит в промежуток [1; 10]\n");
Зачем здесь перевод на новую строку - если WriteLine это и так сделает?

2023-11-18 19:47 UTC, wildpioneer commented on TMS_AQA/Program.cs
> +                                Console.WriteLine("Число входит в промежуток [10; 40]\n");
Зачем здесь перевод на новую строку - если WriteLine это и так сделает?

2023-11-18 19:47 UTC, wildpioneer commented on TMS_AQA/Program.cs
> +                    Console.WriteLine("Ошибка! Неверный формат ввода, введите число!\n");
Зачем здесь перевод на новую строку - если WriteLine это и так сделает?

2023-11-18 19:47 UTC, wildpioneer commented on TMS_AQA/Program.cs
> +                string[,] dictionaryToTranslate = new string[2, 10]{
К данному уроку мы еще не знаем массивов - ну да ладно

2023-11-18 19:47 UTC, wildpioneer commented on TMS_AQA/Program.cs
> +                for (int i = 0; i < dictionaryToTranslate.GetLength(1); i++)
Блок инициализации данных закречен - и луше вставить пустую строку

2023-11-18 19:47 UTC, wildpioneer commented on TMS_AQA/Program.cs
> +                    Console.WriteLine("Ошибка! Неверный формат ввода, введите число!\n");
Зачем здесь перевод на новую строку - если WriteLine это и так сделает?

2023-11-19 05:32 UTC, vashaferov commented on TMS_AQA/Program.cs
> +while (flag)
Можно и через "do", тут скорее привычка из WPF, использовал чаще вот и привык

2023-11-19 05:33 UTC, vashaferov commented on TMS_AQA/Program.cs
> +                    Console.Write("Введите второе число: ");
Учту

2023-11-19 05:35 UTC, vashaferov commented on TMS_AQA/Program.cs
> +                                Console.WriteLine($"{firstNum} / {secondNum} = Ошибка! Делить на ноль нельзя!\n");
Отвечу сразу на все комментарии ниже, для отступа в консоли (пустая строка), для эстетики, не более

2023-11-19 05:36 UTC, vashaferov commented on TMS_AQA/Program.cs
> +                for (int i = 0; i < dictionaryToTranslate.GetLength(1); i++)
Учту

2023-11-19 05:42 UTC, vashaferov commented on TMS_AQA/Program.cs
> +                string[,] dictionaryToTranslate = new string[2, 10]{
Но и в задаче не было указано что ими нельзя пользоваться, а мне просто хотелось их вспомнить для себя

2023-11-27 19:35 UTC, wildpioneer commented on TMS_AQA/Program.cs
> +                string[,] dictionaryToTranslate = new string[2, 10]{
Ok

2023-11-27 19:35 UTC, closed without merging