Array homework
vashaferov/TMS_AQA pull request #2
Opened 2023-11-20 08:02 UTC by vashaferov

ДЗ "Массивы" 1-12

2023-11-27 19:44 UTC, wildpioneer requested changes

2023-11-27 19:44 UTC, wildpioneer commented on Array/Program.cs
> +                    array1[i] = new Random().Next(10);
Необычно. Но все же лучше в начале проинициализировать массив - затем его вывести чтобы можно было понять какое число вводить для решения задачи

2023-11-27 19:44 UTC, wildpioneer commented on Array/Program.cs
> +                    meanNum += array1[i];
Название переменной мне не нравиться - не могу понять из названия для чего она

2023-11-27 19:44 UTC, wildpioneer commented on Array/Program.cs
> +                Console.WriteLine("Среднее значение: " + meanNum / sizeArray);
Это получается среднее арифметическое  - а надо среднее значение
1 5 10 - среднее 5, а арифметическое 5.3

2023-11-27 19:44 UTC, wildpioneer commented on Array/Program.cs
> +                    if (i % 2 == 0)
Очень сложно - можно просто в самом цикле for проставить не i++, а i = i + 2;

2023-11-27 21:35 UTC, vashaferov commented on Array/Program.cs
> +                    array1[i] = new Random().Next(10);
Понял, учту.

2023-11-27 21:37 UTC, vashaferov commented on Array/Program.cs
> +                Console.WriteLine("Среднее значение: " + meanNum / sizeArray);
Так и думал. Значит неправильно интерпретировал условие задачи

2023-11-27 21:40 UTC, vashaferov commented on Array/Program.cs
> +                    if (i % 2 == 0)
И правда, переусложнил

2023-11-27 21:44 UTC, vashaferov commented on Array/Program.cs
> +                    meanNum += array1[i];
Mean - среднее значение

2023-12-11 13:50 UTC, wildpioneer commented
Проверено

2023-12-11 13:50 UTC, closed without merging