Strings homework
vashaferov/TMS_AQA pull request #3
Opened 2023-11-26 08:55 UTC by vashaferov

Домашнее задание по теме "Строки"

2023-11-27 19:50 UTC, wildpioneer requested changes

2023-11-27 19:50 UTC, wildpioneer commented on StringApp/Program.cs
> +                            for (int i = 0; i < text.Length; i++)
Как личное решение - пойдет. Но есть char.IsDigit()

2023-11-27 19:50 UTC, wildpioneer commented on StringApp/Program.cs
> +                            foreach (string s in sArray)
Тоже не обычное решение - респект.
Но Join подошел бы лучше

2023-11-27 19:50 UTC, wildpioneer commented on StringApp/FiveTask.cs
> +            if (Regex.IsMatch(s, pattern))
Чуточку не верно, это будет проще
return Regex.IsMatch(s, pattern)

2023-11-27 21:48 UTC, vashaferov commented on StringApp/FiveTask.cs
> +            if (Regex.IsMatch(s, pattern))
И правда, метод же и так вернет true или false

2023-11-27 21:50 UTC, vashaferov commented on StringApp/Program.cs
> +                            for (int i = 0; i < text.Length; i++)
Совсем забыл про него, возьму на заметку

2023-11-27 21:51 UTC, vashaferov commented on StringApp/Program.cs
> +                            foreach (string s in sArray)
Понял, учту

2023-12-11 13:51 UTC, wildpioneer commented
Проверено

2023-12-11 13:51 UTC, closed without merging